### ISSUE TITLE
Flickering Bug

### ISSUE THREAD

**Issue by rogermarket** [damianmgarcia/Hide-n-Seek#16] opened 2023-06-16 20:55 UTC
I'm not sure how else to describe it, but this extension seems to have a bug that causes the LinkedIn page to "flicker"/reload constantly, and sometimes the job listing itself simply disappears (becomes completely hidden). I can't browse jobs in this environment because portions of the screen or the entire screen continue to reload or disappear at random.

**Comment by damianmgarcia** [comment] 2023-06-17 00:50
rogermarket, I'm sorry that you're experiencing this flickering issue but I'll do my best to resolve it. Thank you for bringing it to my attention! I have a few suggestions and would appreciate any additional details that you're comfortable sharing.

## Reinstall Hide n' Seek
You may have tried this already, but in case you haven't, can you remove and then reinstall Hide n' Seek to see if the issue is still present? If it is still present, the following suggestions may help us get to the bottom of it:

## Share a video recording of the issue
A video recording that demonstrates the issue would be very helpful. There are a few ways to do this:

1. [Screencastify](https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn/related) is a popular and easy-to-use Chrome extension that allows you to record your screen and to easily share the video. Screencastify allows you to record a tab, the browser window, or your whole screen, but only the "whole screen" option is useful for this case. The reason is that the other two options are unable to capture extension popup windows, such as the kind Hide n' Seek uses. After you finish recording, there is a "Share" button that gives you a link, which you can post here so that I can see it.
2. You could also use another screen recorder or even another device, such as a phone or tablet, to record the screen, and then upload the video to YouTube and share the link.

To protect your privacy, if you decide to share a video recording, please be sure to close any tabs or windows that you don't want others to see.

## See if this issue occurs on Indeed
If you use [Indeed](https://www.indeed.com/), can you let me know if you see this flickering problem there as well?

## See if this issue occurs on a different computer or a different browser
If you're able to, try installing Hide n' Seek on a different computer or on a different browser (e.g. Edge instead of Chrome) and see if you still experience this issue.

## Share some details regarding your operating system, browser, Hide n' Seek, and other extensions
It would be helpful to know some details about your system and browser such as:

1. Operating system (e.g. MacOS 10.15, Windows 11, etc.)
2. Browser and browser version (e.g. Chrome 114, Edge 114, etc.)
4. Hide n' Seek version (e.g. 4.2.2, etc. — This can be found by right-clicking the Hide n' Seek icon, then clicking "Manage extension")
5. Other installed extensions (e.g. AdBlock, etc. — This information is helpful to know in case the issue is caused by a conflict between Hide n' Seek and some other extension)

## Check for Hide n' Seek error messages
There may be error messages related to Hide n' Seek. To see them, you have to look at the console within the browser's devtools. On Windows or Linux you can access the console easily with the keyboard shortcut Control+Shift+J, or if you are using a Mac you would use Command+Option+J. Once the console is open, you can either take a screenshot or highlight all the text and then copy and paste it here.

**Comment by damianmgarcia** [comment] 2023-07-23 03:52
Thanks again for reporting this issue.

However, since this issue has not had any activity for 36 days, it will be closed in 9 days (July 31) unless there are new comments.

**Comment by rogermarket** [comment] 2023-07-24 02:12
I'm so sorry for my silence. You sent a bunch of info right before my mom came to town for a week, and I never got a chance to follow up. Also, before I provide info, I should point out that the only option I have to post a comment in this thread is "Close with comment" or "Close as not planned," so it seems like this issue is going to close as soon as I post this comment, but anyway, here goes…

Are you able to see [**this video**](https://vimeo.com/847842606)?

The password is just the word "**hide**" with no caps or punctuation.

Some other info:
1. I did try **reinstalling the Chrome extension**, and that didn't resolve it. I **also tried switching to Incognito mode**, and it still happens; in fact, the video above was recorded while in Incognito mode. I believe I've also **restarted my computer** at least once recently.
2. I don't use **Indeed** much, but when I did try it, the issue didn't come up. However, **sometimes it takes a bit of time** for it to occur on LinkedIn, so it could just be that I wasn't on Indeed long enough for it to come up.
3. I'm running Hide 'n' Seek 4.2.2 in Chrome 114.0.5735.198 on macOS 12.2.1.4. 
4. I'm running these **Chrome extensions**: 1Password, AdBlock, DS Amazon Quick View, Huge Amazon Search Suggestion Expander, KDP / Amazon BSR & Keyword Research SEO Tool, KDSPY, Multiselect for Trello, and Podio Super Menu.
5. See console errors below. I hope these are the right ones.

Console errors:

platform.linkedin.com/litms/vendor/google/gtag-adwords.js?id=AW-851212376:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.facebook.com/tr?id=269782020245380&ev=PageView&&noscript=1:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
utag.js?cb=1690161000000:8 visitor.publishDestinations() result: Attempted to attach and load the destination publishing iframe through this API call. Result: The destination publishing iframe was attached and loaded successfully.
www.facebook.com/:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
5injected.js:17 [USO] Button detection aborting due to timeout.
www.facebook.com/tr?id=269782020245380&ev=PageView&&noscript=1:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/li/track:1     Failed to load resource: the server responded with a status of 400 ()
utag.js?cb=1690161000000:8 visitor.publishDestinations() result: The destination publishing iframe is already attached and loaded.
www.facebook.com/:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.facebook.com/tr?id=269782020245380&ev=PageView&&noscript=1:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
utag.js?cb=1690161000000:8 visitor.publishDestinations() result: The destination publishing iframe is already attached and loaded.
www.facebook.com/:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/companionBubble.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/vendor.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/highcharts.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
11DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/engine.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/support_en_US.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/vendor-static.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/media-player.amd.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/chunk.143.26e9e6cbd8af07f7dfaa.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
4DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/engine-vendor.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/voyager-web.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/chunk.826.24667ac748831372ba1d.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/proj4.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/bigpipe-v2.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://static.licdn.com/sc/h/map.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by damianmgarcia** [comment] 2023-07-24 05:41
**Thank you for your thorough reply and for including the video**. _Wow_, that is definitely an issue. 

### Here is what I have done so far

1. Checked the list of extensions you use for ones that _might_ have an affect on linkedin.com and thus a potential conflict with Hide n' Seek; only 1Password and AdBlock have permission to run on linkedin.com, so I installed them. So far, nothing.
2. Checked the console errors you reported, but none of them look related to Hide n' Seek.
3. Watched the video at least 10-15 times looking for patterns and possible causes.

### Things that remain uncertain about this issue

1. Whether it is specific to LinkedIn or not.
2. Whether it is related to Chrome on MacOS. My guess is probably not, but unfortunately, I don't have a MacOS device to test on.

### Additional questions

1. I assume that it still flickers if you uncheck "Do not display hidden jobs" but can you confirm that?
2. Do you have any other Macs or PCs that you can test on to see if the same issue happens?

I will keep this issue open and continue to try to reproduce it and hopefully get to the bottom of it.

Thanks again for reporting this and supplying a video and other important details. I really appreciate it!

**Comment by rogermarket** [comment] 2023-07-25 23:30
No, I don't have another computer I can test out.

The extension actually seemed to be working OK when I was using it today, so unfortunately I'm still trying to confirm that the issue occurs with the "Do not display hidden jobs" option **unchecked.** Sorry about that. I'll keep trying over the next couple of days and will follow up when I have an answer.

**Comment by damianmgarcia** [comment] 2024-11-02 22:50
Hi! It's been a while, so I'm going to close this issue. However, it can always be reopened if necessary. Thanks again for reporting it! :)

**Closed by damianmgarcia** 2024-11-02 22:50 UTC
